source 'https://rubygems.org'

gem "bcrypt", "3.1.22"
gem "chartkick", "5.2.1"
gem "require_all", "3.0.0"
gem "tzinfo", "2.0.6"

gem "sinatra", "4.2.1"
gem "sequel", "5.101.0"
gem "sqlite3", "2.9.0"
gem "rackup", "2.3.1"
gem "puma", "7.2.0"
gem "rubocop", "1.84.1"

group :test do
  gem "capybara", "3.40.0"
  gem "rack-test", "2.2.0"
  gem "rspec", "3.13.2"
  gem "simplecov", "0.22.0", require: false
end

